[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src", "src"]

[contracts]
StarkVest = ["src/starkvest/starkvest.cairo"]
Token = ["tests/mocks/erc20.cairo"]

[test]
target = ["tests"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.project]
network = "testnet"
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"
block-explorer = "starkscan"

[profile.testnet2.project]
gateway-url = "https://alpha4-2.starknet.io"
chain-id = 1536727068981429685321
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"
block-explorer = "starkscan"

[profile.mainnet.project]
network = "mainnet"
